### ISSUE TITLE
Finalize which elements should be hidden

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise-dmexco#102]

**Comment by peter-gerhard** [comment]
Connects #19
@trangng @mmoelli @lauraluiz @schleichardt
I will merge the old PR. To continue if you have something that should be enabled/disabled put it here
The following are currently disabled. Uncheck the ones that have to be enabled

disabled: 
* [X] thumbnail-quickview
* [X] whichlist stuff
* [X] star rating
* [X] 'Brands tab in menu'
* [X] Broken images in gallery
* [ ] Jumbotron
* [X] Sign in widget
* [ ] Localization widget
* [X] Payment methods on Checkout page
* [X] Follow up checkboxes on Checkout page
* [X] Product Details accordion
* [X] Social media buttons pdp

**Comment by peter-gerhard** [comment]
@trangng should I remove the "view details" link, since most of the products dont have a description?
![screen shot 2015-09-15 at 09 41 06](https://cloud.githubusercontent.com/assets/4236201/9870614/ce499d02-5b8d-11e5-9935-3688acdaeec0.png)

**Comment by trangng** [comment]
@peter-gerhard yes please do
