### ISSUE TITLE
Border around  'like' button

### ISSUE THREAD

**Issue by stremlenye** [sphereio/sphere-sunrise-dmexco#104]
*Env: Chrome Version 45.0.2454.85 (64-bit)*
After clicking `like` (or heart shaped) button it become surrounded with glowing border.
Not sure if it supposed to be so.
![image](https://cloud.githubusercontent.com/assets/586343/9847966/44f229a8-5add-11e5-8de9-0628b67afb1f.png)

**Comment by agourlay** [comment]
+1

**Comment by lauraluiz** [comment]
Wishlist is removed from MVP, should not be appearing anymore.
