### ISSUE TITLE
Wishlist missing images

### ISSUE THREAD

**Issue by stremlenye** [sphereio/sphere-sunrise-dmexco#105]
*Env: Chrome Version 45.0.2454.85 (64-bit)*

![image](https://cloud.githubusercontent.com/assets/586343/9848038/ef9fe318-5add-11e5-9e78-29eec59de48a.png)

```
GET https://sphere-sunrise-dmexco.herokuapp.com/en/img/close.png 404 (Not Found)
GET https://sphere-sunrise-dmexco.herokuapp.com/en/img/hand-bag-2-black.png 404 (Not Found)
GET https://sphere-sunrise-dmexco.herokuapp.com/en/assets/img/blue-shirt.jpg 404 (Not Found)
```

**Comment by yanns** [comment]
The "/en" is probably too much.
https://sphere-sunrise-dmexco.herokuapp.com/assets/img/blue-shirt.jpg works for example

**Comment by lauraluiz** [comment]
How could you access the wishlist? It should not be accessible at all.

**Comment by lauraluiz** [comment]
Okay that was removed in a PR.
