### ISSUE TITLE
mixed HTTPS / HTTP content

### ISSUE THREAD

**Issue by yanns** [sphereio/sphere-sunrise-dmexco#106]
use https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700 instead of http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700 to avoid mixing HTTP and HTTPS resources

**Comment by lauraluiz** [comment]
Actually better `//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700` to avoid selecting protocol.

**Comment by yanns** [comment]
:+1:

**Comment by JulianSamarjiev** [comment]
@lauraluiz  This is done already in the design repo, how should we go about updating the changes?

**Comment by JulianSamarjiev** [comment]
fixed and merged
