### ISSUE TITLE
HTML is escaped in the category description

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#118]
![sunrise_-_tops](https://cloud.githubusercontent.com/assets/156569/9849398/0102c712-5aeb-11e5-9689-b5ac60083b3f.png)

**Comment by OlegIlyenko** [comment]
Either description should not contain HTML or we should not escape it, I guess

**Comment by lauraluiz** [comment]
@trangng will fix this removing the HTML from description. We can allow HTML in the template, but we don't need it right now and can cause some layout disasters.

**Comment by trangng** [comment]
HTML are removed
