### ISSUE TITLE
A gap between header section and menu closes menu is mouse is moved slowly

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#126]
When I move mouse in the marked area, menu closes itself. It only works when I move mouse very quickly. With the normal mouse movement speed I can't access the menu

![sunrise_-_skirts](https://cloud.githubusercontent.com/assets/156569/9849823/c2f07ea2-5aee-11e5-8155-10573a8c32c3.png)

**Comment by OlegIlyenko** [comment]
ref #117

**Comment by ct-jensschulze** [comment]
Fixed in sunrise-design

See https://github.com/sphereio/sphere-sunrise-design/issues/115

**Comment by OlegIlyenko** [comment]
:+1:
