### ISSUE TITLE
Broken layout because of the missing images

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#127]
Missing images (is it issue on itself?) destroy the list view layout. Maybe it can be fixed by explicitly specifying the size of item or item image in the CSS?

![sunrise_-_shoes](https://cloud.githubusercontent.com/assets/156569/9849924/82e426fa-5aef-11e5-9f68-365b37e3b568.png)

**Comment by lauraluiz** [comment]
Solved by #136
