### ISSUE TITLE
No form validation for checkout

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#130]
I tried to enter incorrect email address and it worked. Also when I leave it empty the page refreshes (it does not go to the next step, but I don't see any validation error)

**Comment by schleichardt** [comment]
The template lacks the unhappy paths.

**Comment by schleichardt** [comment]
@lauraluiz should we at least try to hack sth. into the flash messages?

**Comment by lauraluiz** [comment]
Show submitted form and a generic message error "the form contains errors" kind of.
