### ISSUE TITLE
String translations/localizations missing

### ISSUE THREAD

**Issue by rzenner** [sphereio/sphere-sunrise-dmexco#132]
On the category page, there are still strings such as "pop.displaySelectorText" or "POP.CLEARTEXT"

**Comment by trangng** [comment]
@lauraluiz where can I change this text?

EN: CLEAR
DE: LÖSCHEN

**Comment by lauraluiz** [comment]
https://github.com/sphereio/sphere-sunrise-dmexco/blob/master/conf/messages.en#L105

**Comment by trangng** [comment]
thx, added to german also
