### ISSUE TITLE
Order number generation

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise-dmexco#135]
@lauraluiz The order generation uses random numbers, should this be a sequence?

**Comment by lauraluiz** [comment]
@mmoelli should we force it sequential (using custom objects with concurrency control) and nice or can it be random (e.g. based on timestamp)?

**Comment by mmoelli** [comment]
Would leave it with random numbers for the dmexco. For the original sunrise implementation we need a more distinct solution.
