### ISSUE TITLE
Translation: Missing translation in the cart-page

### ISSUE THREAD

**Issue by adnasa** [sphereio/sphere-sunrise-dmexco#138]
Missing translation in the cart page

![img](https://d1ro8r1rbfn3jf.cloudfront.net/ms_84541/9yV42QWTyky3gy0CHIhFWegMAYXMUa/Sunrise%2B-%2BCart%2BPage%2B2015-09-14%2B16-04-24.png?Expires=1442325959&Signature=MBTbWiFKM08M45S2~sd-XcwxPmLQH1kDTU-ZjTUasuwWzLSz8PM2Q7NKTc1ga0Z4sRObxyaRcGp56cWudDzas9QwXRG1nEw9XEhXihtpjWIFyxDLt7IPLgGsY97TaO37am~LJ5n0KYTmFFXjyqm25Z~BxfkVX0jPvdgY23EURaX6mDaXdRQUIUUYbzVNbRdZ9Suna7JJUzVTta0q25RDVVdqWRbUg068hUjkUCVCxOpT2yK4huG9R4aFRQsTXmPct~kCSnKOfbN6uCXeuBW8zZ41S2U7myXd6ggIXfGUrpMUfSoPpYneEDQwH-gApWslyg6e5u2XEqLZ2bWU-It~9Q__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by mmoelli** [comment]
Almost done: https://sphere-sunrise-dmexco.herokuapp.com/de/cart

Who is taking care of the rest?

**Comment by trangng** [comment]
I added german translation for form.delete = Entfernen, I think that's it right? @mmoelli
