### ISSUE TITLE
Translation: Missing translation in the footer when language-setting is german

### ISSUE THREAD

**Issue by adnasa** [sphereio/sphere-sunrise-dmexco#139]
![img](https://d1ro8r1rbfn3jf.cloudfront.net/ms_84541/JoKTOsaAyqjIz15THMsdjxMAj4OEpz/Sunrise%2B-%2BParf%25C3%25BCm%2B%25E2%2580%259EEscentric%2B02%25E2%2580%259D%2BEscentric%2BMolecules%2B30ml%2B2015-09-14%2B16-08-29.png?Expires=1442326138&Signature=XX0zo87uRgqc2Fk37jMnA9bbtlD29W3HA9X4~NEJ5irM9MzZCBRDDlqTT7pSQ1NjBmm4akkcjRomh9hfSL6jPCqdqAbzGuhFas4sHZKbERfXYmwQybFUhJdg0EPnuyP-mh4Ldpbg6NZ4Zw21Cff9uv7t3vZDq76tnQcpdNxPLPQOTFzjEPk1WzNR8TQC3gvGev7xcF263VMTc1HVPgyFnMlr6zdTc64eIZJWDgwQuDaSvHRAUOAhlQf7NllhbD64iUjypYVfXpl1fDor42CDuj2YJ2o~S3rnJCN9vVK~fCe9ikOLvRYN9vBHKsN21rRhoXoXuMOI15hDQWq0VrWn3Q__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by trangng** [comment]
@peter-gerhard I can change these in the messagefiles right?

**Comment by peter-gerhard** [comment]
@trang yes you can :)

**Comment by schleichardt** [comment]
This is the same as #149, right?

**Comment by trangng** [comment]
yes, I close it
