### ISSUE TITLE
Search result page: Changing some settings overrides the search query

### ISSUE THREAD

**Issue by adnasa** [sphereio/sphere-sunrise-dmexco#141]
##### Problem

Basically after searching i.e. a jacket, I get a result page which is great.
But when updating the page-size filter, it overrides my filter and shows "new" product in the new result-list

__before__
![image-1](https://d1ro8r1rbfn3jf.cloudfront.net/ms_84541/DvcYNyKYMUq4DfA6nts32MG1v6pbHM/Sunrise%2B-%2BSuche%253A%2B%2522Jacken%2522%2B2015-09-14%2B16-16-37.png?Expires=1442326624&Signature=ca~62oaSkawXdgqnzosgnx~EKkZPajg1IE20WFQlVsE1AVAnK5H9QurTD6g~qVzLJnyhS9lGmXW8hig8PDSbb-SrJmB7xHq0CNG1-2DNEJRY-DFWRGChXzgO~TlStWL57cJ2209liYPFIIhrc4mTmU60iA92cT0Kj6lHfGyNOEBLJb4vVj2T14lQnn5ISea~S3349DG57N7esPKEcNH1fQKJvcR4FsIU4FenJwWxn1ZyuzDYcnLKD~7sFTACBwNkSfXkah1rRHrtO01d~au5eEY3jH24UlSGNZzfkwQ05a762ldwcxjceAcRdfkOeDXdWOvvJVcc6ZBfFmVWvd3NtQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

__after__
![image-2](https://d1ro8r1rbfn3jf.cloudfront.net/ms_84541/ODLyu0j1tBklMfzJUZs3qalNy9YrBq/Sunrise%2B-%2BSuche%253A%2B%2522%2522%2B2015-09-14%2B16-19-15.png?Expires=1442326791&Signature=Ye7M1vPGjcGigWjbtjKNRFQ9kBpGTon1lHboXtgrJY2TxhojjkuQCOX97~4Hk2UQEJaYI91yMzyDbcc-cQ0213Sgk1q8e9-YjOttkZmZwnM0zL1LkUvrrPAXFj04QJeZncH-enpssvpXZxjYnw6tDulepTVV8rIlU3Lt8Fpjos3pyiuRXyYe~FK4e3fU5oPeXpNSuWI8W-awHZHNnjfpMtRNKt3OjRhWImwAvlcK6nrJhDe0Je3DiIva0r4zmu3mgWH9ZRW-eC-0lLAxQkRSCXKFmXq4MGPBhHJGL5pVlz2nbb22XKi1gD~ECqeTWpM516Ra9KI2pands3MNWDmtMA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by adnasa** [comment]
The same bug occurs when updating the sort filter

**Comment by lauraluiz** [comment]
Solved by #100
