### ISSUE TITLE
Sorting after performing search resets the search critetia

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#144]
Steps to reproduce

1. search for something that, let's say, produces 500 search results (with full text search field at the top right)
2. sort by "Price low to high" (or any other sort criteria)

the result list suddenly contains all 30000 products instead expected 500

**Comment by lauraluiz** [comment]
Solved by #100

**Comment by OlegIlyenko** [comment]
:+1:
