### ISSUE TITLE
broken product images on home under suggestions

### ISSUE THREAD

**Issue by trangng** [sphereio/sphere-sunrise-dmexco#145]
![screen shot 2015-09-14 at 17 08 29](https://cloud.githubusercontent.com/assets/5373189/9853410/c2fdabda-5b03-11e5-83c9-098397287e50.png)

**Comment by peter-gerhard** [comment]
@trang from which categories should the shown products be?

**Comment by trangng** [comment]
@peter-gerhard  random product from category "NEW"
