### ISSUE TITLE
Payment method missing on Checkout - Payment page

### ISSUE THREAD

**Issue by trangng** [sphereio/sphere-sunrise-dmexco#148]
I'd at least add prepayment otherwise the page looks strange.

![screen shot 2015-09-14 at 17 19 35](https://cloud.githubusercontent.com/assets/5373189/9853631/db4f1920-5b04-11e5-8016-c1c85d055b3c.png)

**Comment by schleichardt** [comment]
That was implemented and then you suggested peter to remove the payment methods.
Then I discovered and fixed it in a pull request (not yet deployed).

https://github.com/sphereio/sphere-sunrise-dmexco/pull/137/files#diff-1c3417353a6abca6117295b1ac7a99b8L25

**Comment by trangng** [comment]
I told him to hide paypal and credit card, but not all. Thanks for fixing
