### ISSUE TITLE
remove button on confirmation page

### ISSUE THREAD

**Issue by trangng** [sphereio/sphere-sunrise-dmexco#150]
I think it's the empty button from the checkout:

![screen shot 2015-09-14 at 17 21 39](https://cloud.githubusercontent.com/assets/5373189/9853716/5c1fa7f4-5b05-11e5-8521-e04d6436908e.png)

**Comment by schleichardt** [comment]
I think this has been addresses in a pull request. But let's check again after the merges.

**Comment by schleichardt** [comment]
fixed
