### ISSUE TITLE
Handling of big carts

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#158]
At the moment the number overflows a circle is cart has too many items:

![sunrise_-_blazer](https://cloud.githubusercontent.com/assets/156569/9856289/096a22dc-5b14-11e5-97d8-d5e67dbfbf62.png)

What is more important is that I get 500 is I try to view such cart:

![error](https://cloud.githubusercontent.com/assets/156569/9856312/2515359e-5b14-11e5-9eb0-3962e8dee8b1.png)

**Comment by lauraluiz** [comment]
No edge cases for dmexco's scope. The shop should not allow so many items in cart.
