### ISSUE TITLE
Cart calculation seems to be broken

### ISSUE THREAD

**Issue by rzenner** [sphereio/sphere-sunrise-dmexco#162]
Pls take a look the values in the screenshot - it's not intuitive what means what and the values don't add up.

<img width="1162" alt="bildschirmfoto 2015-09-15 um 10 29 41" src="https://cloud.githubusercontent.com/assets/3097492/9871620/27be23e2-5b95-11e5-898e-1dd4967eb8e0.png">

**Comment by trangng** [comment]
@rzenner to update the quantity you need to click on "edit" for now. will be change in general.

total price is the sale price and actually "price" should be sale price as well 318,50
next to it on the left should be the old price like here in HTML:

![screen shot 2015-09-15 at 10 40 40](https://cloud.githubusercontent.com/assets/5373189/9871954/4e738918-5b96-11e5-9122-bfaffcb43d52.png)

**Comment by schleichardt** [comment]
internal: http://localhost:9000/en/herno-downjacket-PI0169U192887800-olive-M0E20000000DJ1L.html

**Comment by schleichardt** [comment]
I have a different data but it is other wrong.

![screen shot 2015-09-15 at 11 01 20](https://cloud.githubusercontent.com/assets/1320833/9872357/29b2be0c-5b99-11e5-8d32-a94c008aa796.png)

The subtotal is bigger than the total.

**Comment by mmoelli** [comment]
I guess 455 is the original price while 637 is the discounted price for 2 items. The subtotal seems to be generated from the original price (2*455=910).

**Comment by schleichardt** [comment]
@mmoelli @lauraluiz  we need more price display helpers in the backend, it is super error prone to show this data.
Showing the cart data is a very common use case.

I looked for `lineItem.discountedPrice` (which I expected to contain the discounted price...) and if not present used the price `lineItem.price` of the line item. 
The thing is `lineItem.discountedPrice` is for CART discounts and I need to check also `lineItem.price.discounted`.

**Comment by schleichardt** [comment]
I would love to have a field `effectiveAmount` which is the monetary amount to pay per item and a field `oldAmount` which contain the monetary amount for the old price.

**Comment by schleichardt** [comment]
This is how it will look:

![screen shot 2015-09-15 at 11 45 57](https://cloud.githubusercontent.com/assets/1320833/9873385/aabfb5bc-5b9f-11e5-9e8d-8d15516d2bb5.png)

**Comment by trangng** [comment]
:+1:
