### ISSUE TITLE
"Join our newsletter" element to remove?

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise-dmexco#182]
@lauraluiz there is a form which does not work

![screen shot 2015-09-15 at 14 50 17](https://cloud.githubusercontent.com/assets/1320833/9876816/2157ca52-5bb9-11e5-8db5-c122a4a2bea1.png)

**Comment by lauraluiz** [comment]
@trangng should we remove all newsletter stuff, I guess?

**Comment by trangng** [comment]
I think it's not necessary. If I put a mail address then page reloads that's fine. we won't show any confirmation emails anyways.

**Comment by schleichardt** [comment]
So we can close it?
