### ISSUE TITLE
Hide non-functional elements

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-sunrise-dmexco#19]

**Comment by peter-gerhard** [comment]
@trangng can you provide a list of elements, that should be hidden?
e.g. wish list, reviews, etc

**Comment by peter-gerhard** [comment]
so far i have
- wish list related stuff
- search box
- star rating on pdp
- 'Brands' tab in navigation
- broken thumbs in gallery

**Comment by mmoelli** [comment]
I would add:
* Top Banners on category page
* Sign-In Button

**Comment by peter-gerhard** [comment]
@trangng if you could have a final look, we could merge this

**Comment by trangng** [comment]
@peter-gerhard ok I do now

**Comment by trangng** [comment]
@peter-gerhard  I'dd hide these additional 

- hide languages which are not available
- "edit" on cart
- payment methods (credit card and paypal) or no one should click on then...

thx

**Comment by peter-gerhard** [comment]
@schleichardt isn't the edit already working? is there just a link missing maybe?

**Comment by schleichardt** [comment]
Yes, the edit button it is working, don't hide it, please.

**Comment by schleichardt** [comment]
Due to such misunderstands it would have been a good idea to have a short demo meeting.

**Comment by lauraluiz** [comment]
The edit button for cart was always planned from the beginning as MVP for dmexco, it is in the task list.

**Comment by trangng** [comment]
with edit button customer should be able to change the amount, size and colour of the product directly in cart. As far as I remember since we doesn't have that in the HTML yet I thought we should hide it. I thought we said we link the edit button on checkout overview page to checkout-payment and checkout-address etc. but it's fine like this too for dmexco.

**Comment by schleichardt** [comment]
this also should be removed:
```
Save my details to create my personal account at SUNRISE
Please add me to the SUNRISE Newsletter
```
on http://sphereio.github.io/sphere-sunrise-design/checkout-confirmation.html

**Comment by lauraluiz** [comment]
@trangng the edit button is used currently to modify the quantity in the cart, there is no other way to do it without AJAX. That's why it was decided to change the quantity selector for a dropdown selector, but it was never implemented.

**Comment by mmoelli** [comment]
Please also hide "Product Details" on PDP as it seems we're not having data for this.

**Comment by mmoelli** [comment]
Same goes for the social buttons on the PDP

**Comment by yanns** [comment]
@lauraluiz I also though "edit" was not working properly.
I was expected the quantity to be changed when I click on the `-` and `+` buttons.
