### ISSUE TITLE
cart discounts cause exceptions

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise-dmexco#213]

**Comment by peter-gerhard** [comment]
@schleichardt can you provide any info how to reproduce?

**Comment by schleichardt** [comment]
You create a cart discount and create a situation where the cart discount applies. And then do the checkout.

**Comment by schleichardt** [comment]
I think it is related to https://github.com/sphereio/sphere-jvm-sdk/issues/711

Laura will provide a fix

**Comment by peter-gerhard** [comment]
@lauraluiz i found a quick fix for now adding an extra null check

**Comment by lauraluiz** [comment]
We didn't try with the fix we did yesterday if it's working. What extra null check is that?

**Comment by peter-gerhard** [comment]
before
`final boolean hasCartDiscount = lineItem.getDiscountedPrice() != null`
after
`final boolean hasCartDiscount = lineItem.getDiscountedPrice() != null && lineItem.getDiscountedPrice().getMoney() != null;`

**Comment by peter-gerhard** [comment]
@trangng 
I would expect to see discount as negative number in red, the formatting doesn't look good though. I would leave it a positive number for now:
![screen shot 2015-09-16 at 10 09 55](https://cloud.githubusercontent.com/assets/4236201/9899662/9da2f4a4-5c5b-11e5-9812-bce65d1f1621.png)

**Comment by lauraluiz** [comment]
@peter-gerhard that's weird. If you are using `getDiscountedPrice.getMoney` you are using an old version of the JVM SDK which always had `getMoney` null. So `hasCartDiscount` would always be false.
