### ISSUE TITLE
Translate Categories

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise-dmexco#80]
Please translate the following categories in the data since they are on the homepage
external id / current slug (en)
55 / men-shoes-schnuerschuhe
22 / women-clothing-oberteile
52 / men-clothing-t-shirt   <-- (plural pls)
38 / women-shoes-boots
140 / accessories-women-sonnenbrillen
24 / women-clothing-t-shirts

**Comment by peter-gerhard** [comment]
@hajoeichler
could you also rename the categories 'men' and 'women' so that there names are not upper case
"MEN" -> "men"
thx

**Comment by hajoeichler** [comment]
What is missing here?

**Comment by peter-gerhard** [comment]
http://sphere-sunrise-dmexco.herokuapp.com/de/men
on the jumbotron there should be a german translation "Herren". 'Men' and 'Woman' might be missing a german translation.

http://sphere-sunrise-dmexco.herokuapp.com/en/women-shoes-winterboots 
'winter boots' should be two words

http://sphere-sunrise-dmexco.herokuapp.com/de/women-shoes-winterboots
jumbotron should also have a german translation

**Comment by trangng** [comment]
@peter-gerhard @hajoeichler I changed it
