### ISSUE TITLE
Discuss relationship filters vs. search

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-sunrise-dmexco#92]
I know we talked about that but I would like to discuss how we can bring this together.

e.g. Zalando:
Search for "jeans" = https://www.zalando.de/damen/?q=jeans&qf=1
Additional brand filter = https://www.zalando.de/damen/7-for-all-mankind/?q=jeans

So I can actually limit my filter results which makes sense with the amount of data sets. WDYT?

**Comment by lauraluiz** [comment]
Solved by #100
